# Generated by Django 2.2.9 on 2020-04-28 18:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200124_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('Image', wagtail.images.blocks.ImageChooserBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('block_quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(help_text='The Text to be Quoted')), ('author', wagtail.core.blocks.CharBlock(help_text='Source of quote'))])), ('two_column_block', wagtail.core.blocks.StructBlock([('background', wagtail.core.blocks.ChoiceBlock(choices=[('orange-full', 'orange'), ('shared-section', 'green')])), ('left_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embedded_video', wagtail.embeds.blocks.EmbedBlock())], icon='arrow-left', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embedded_video', wagtail.embeds.blocks.EmbedBlock())], icon='arrow-right', label='Right column content'))])), ('four_column_block', wagtail.core.blocks.StructBlock([('background', wagtail.core.blocks.ChoiceBlock(choices=[('orange-full', 'orange'), ('shared-section', 'green')])), ('block_title', wagtail.core.blocks.CharBlock(classname='block title')), ('block_subtitle', wagtail.core.blocks.CharBlock(classname='block subtitle')), ('first_column', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='description')), ('subheading', wagtail.core.blocks.CharBlock(classname='sub description')), ('bigtext', wagtail.core.blocks.CharBlock(classname='bigtext')), ('toplist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='top list'))), ('bottomlist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='bottom list')))])), ('second_column', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='description')), ('subheading', wagtail.core.blocks.CharBlock(classname='sub description')), ('bigtext', wagtail.core.blocks.CharBlock(classname='bigtext')), ('toplist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='top list'))), ('bottomlist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='bottom list')))])), ('third_column', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='description')), ('subheading', wagtail.core.blocks.CharBlock(classname='sub description')), ('bigtext', wagtail.core.blocks.CharBlock(classname='bigtext')), ('toplist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='top list'))), ('bottomlist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='bottom list')))])), ('fourth_column', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='description')), ('subheading', wagtail.core.blocks.CharBlock(classname='sub description')), ('bigtext', wagtail.core.blocks.CharBlock(classname='bigtext')), ('toplist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='top list'))), ('bottomlist', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(classname='bottom list')))]))]))], blank=True, null=True),
        ),
    ]
